### ISSUE TITLE
How can I get the return Imgur-photo's jpg?

### ISSUE THREAD

**Issue by theochoi93** [AKiniyalocts/imgur-android#10]
I have to upload a photo in Imgur.
But I want to my app can get the upload Imgur-photo's jpg.
Please help me!

**Comment by ghost** [comment]
What do you mean ? get the URL of the image you have uploaded ? Imgur I believe uploads images as PNG rather than JPG

**Comment by AKiniyalocts** [comment]
If thats the case, your URL will be returned in the response from the upload. If you wish to "download" that image to the device, the simplest way to do that would be via the DownloadManager: https://developer.android.com/reference/android/app/DownloadManager.html

**Comment by theochoi93** [comment]
My English is not good enough. Sorry about that. 
Yes,I want to get the URL of the image. 
But I do not want to get this->http://imgur.com/1e8aZn7?r
I want to get ->http://i.imgur.com/1e8aZn7.jpg
I want to return the link(http://i.imgur.com/xxxxxxxx.jpg) in my text box.

**Comment by AKiniyalocts** [comment]
You are able to get more detailed information about the image via another REST call to [imgur's api](http://api.imgur.com/endpoints/image#image) using the uploaded image's id **1e8aZn7**. See the [response object](http://api.imgur.com/models/image)
