### ISSUE TITLE
Gradle Not Working

### ISSUE THREAD

**Issue by ramisaban1** [AKiniyalocts/imgur-android#16]
Hello,

Step 1: git clone https://github.com/AKiniyalocts/imgur-android.git
Step 2: Import into Android Studio
Step 3: The project doesn't sync correctly.

I tried searching up how to fix this issue, but no matter which forum I try, nothing manages to make the project successfully sync.

View the attached picture:
![image](https://user-images.githubusercontent.com/30821900/67028583-98954680-f0d9-11e9-9ffd-88bca9d4a6dd.png)

**Comment by AKiniyalocts** [comment]
This project has not been updated in 4 years and most likely won't be until I have some free time. PR's are welcome.
