### ISSUE TITLE
No resource found that matches the given name 

### ISSUE THREAD

**Issue by tomer1** [AKiniyalocts/imgur-android#7]
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by ghost** [comment]
I assume that is the error you are getting?

Try this:http://stackoverflow.com/questions/32075498/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name

**Comment by tomer1** [comment]
fixed, upgrade SDK to 23

**Comment by ghost** [comment]
Your welcome

**Comment by ghost** [comment]
You're*
