### ISSUE TITLE
Copy link on upload notification 

### ISSUE THREAD

**Issue by ghost** [AKiniyalocts/imgur-android#8]
Hi,

There seems to be an issue with the copy link option, basically if you upload 3 images it only actually copies the URL of the first one rather then the subsequent ones. Until you reboot.

Thanks

**Comment by ghost** [comment]
Fixed this by changing the pending intent line to

```
    PendingIntent pIntent = PendingIntent.getActivity(mContext.get(), 0, shareIntent, PendingIntent.FLAG_CANCEL_CURRENT);
```

**Comment by AKiniyalocts** [comment]
Thanks for sorting that bug out!
