### ISSUE TITLE
Fail upload

### ISSUE THREAD

**Issue by firestork** [AKiniyalocts/imgur-android#9]
I download proj and run in my Android studio. upload always fail :'( can u check api?

**Comment by ghost** [comment]
You need to register your application within Imgur and get the API keys and things, put them into this and then it will work it doesn't work "out of the box"

From the "Cofiguration" section of the Read Me

In Constants.java add your imgur Client API key in the static field: MY_IMGUR_CLIENT_ID

Register Application here: https://api.imgur.com/oauth2/addclient
